#!/bin/bash

# break on errors
set -e
set -x

# Bash: To prepend conda env and make `conda` work flawlessly.
conda init bash

# Bash: Enable color prompt.
sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/' ~/.bashrc

# Bash: readline goodies:
cat > ~/.inputrc <<-'EOF'
	# Preserve existing behavior (eg. word-back).
	$include  /etc/inputrc
   
	"C-xC-r": re-read-init-file
	## arrow up
	"\e[A":history-search-backward
	## arrow down
	"\e[B":history-search-forward
EOF

# # Install a JupyterLab extensions for JupyterLab < 1.0!!
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
jupyter labextension install jupyterlab-jupytext@0.19  # https://github.com/mwouts/jupytext/issues/276
jupyter labextension install jupyter-matplotlib qgrid

# Jupytext noteboo icon: https://github.com/mwouts/jupytext
jupyter notebook --generate-config
echo 'c.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py

# `papermill` cmd below needs `wltp` installed on PYTHONPATH.
pip install -e .[test]

## Re-create `*.ipynb` files from the paired `*.Rmd` files.
./Notebooks/recreate_ipynbs.sh
## Populate pyalgo DB
./Notebooks/recreate_pyalgo_h5.sh


## Import the workspace into JupyterLab
#  From https://github.com/ian-r-rose/binder-workspace-demo/
#  BUT will work at least after jupyterlab >1.0.0a8 
#  (see ian-r-rose/binder-workspace-demo#1)
#jupyter lab workspaces import binder/workspace.json
