#!/bin/bash

# break on errors
set -e
set -x

# Bash: To prepend conda env and make `conda` work flawlessly.
conda init bash

# Bash: Enable color prompt.
sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/' ~/.bashrc

# Bash: readline goodies:
cat > ~/.inputrc <<-'EOF'
	# Preserve existing behavior (eg. word-back).
	$include  /etc/inputrc
   
	"C-xC-r": re-read-init-file
	## arrow up
	"\e[A":history-search-backward
	## arrow down
	"\e[B":history-search-forward
EOF

# Convert Rmd files into Ipynbs
jupytext --to ipynb Notebooks/*.Rmd
# Fix "ipynb" later than Rmd" error on launch
rm Notebooks/*.Rmd

# # Install a JupyterLab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid jupyter-matplotlib

## Import the workspace into JupyterLab
#  From https://github.com/ian-r-rose/binder-workspace-demo/
#  BUT will work at least after jupyterlab >1.0.0a8 
#  (see ian-r-rose/binder-workspace-demo#1)
#jupyter lab workspaces import binder/workspace.json
