#!/bin/bash

## From https://github.com/ian-r-rose/binder-workspace-demo/
# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json \
  --NotebookApp.base_url=user/${JUPYTERHUB_USER} --name=""

exec "$@"
